### PR TITLE
Bump to next release v5.0.0 

### LINKED ISSUE #46: Typescript support?

### LINKED ISSUE #56: Provide own filesystem
Right now koa-ejs uses only actual node's filesystem.

This becomes trouble when using it with [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware).

My case: I have server that uses dev middleware to manage compilation for client-side javascript. It keeps all generated assets in memory. I am able to access it's memory filesystem via `devMiddlewareInstance.fileSystem` which is [memfs](https://github.com/streamich/memfs) node's `fs` api compliant fs.

But koa-ejs accepts only path to root.

So, solution is either to add `fs` property to koa-ejs options which will accept any node's `fs` api compliant type. Or second way is to provide root as callback of type `(templateFilename: string) => Promise<string>`, like: `root: (templateFilename) => myfs.readFilePromise(templateFilename)`.

What do you think?

### LINKED ISSUE #58: Upgrade ejs to v3.x
`ejs` 3.x drops support for Node 4 and 6, and it removes `require.extensions` which previously caused an annoying warning in webpack bundles: https://github.com/mde/ejs/issues/412.

Since this package already requires Node `>= 7.6`, I don't think this upgrade should warrant a major version bump.

### PR DESCRIPTION
**Pull request by 3imed-jaberi**
Fix #46 #58 #59 #60.

### CODE REVIEW

**Comment by 3imed-jaberi** [comment]
@dead-horse, please take a look here and bump the module to v5.

**Review by 3imed-jaberi — COMMENTED** [review]
@titanism, I have solved all the issues in the repo and this PR is ready to be merged and bumped to v5.0.0 🎉! Please add me to npm contributors and give me access to publish it.

**Comment by titanism** [comment]
@dead-horse can you please add "titanism" to npm via `npm owner add titanism koa-ejs`?  Not sure what @3imed-jaberi npm username is, it doesn't match their GitHub's.

**Comment by 3imed-jaberi** [comment]
@titanism, my NPM username matches my GitHub username ... it's [`3imed-jaberi`](https://www.npmjs.com/~3imed-jaberi)!

**Pull request merged**
