### PR TITLE
use co-ejs

### PR DESCRIPTION
**Pull request by nswbmw**

### CODE REVIEW

**Comment by dead-horse** [comment]
what's the difference between `co-ejs` and `ejs`?

**Comment by nswbmw** [comment]
see [merge](https://github.com/koajs/ejs/blob/master/index.js#L42), everytime render a view, if `locals` contain 100 generatorFunctions, `merge` will exec those 100 functions continuously, then send results to `render`. use `co-ejs`, view will take only what it need, and exec functions in parallel. see [co-ejs](https://github.com/nswbmw/co-ejs#example).

**Comment by jeromemacias** [comment]
What is the status of this PR ?

**Comment by nswbmw** [comment]
Closed. You can use co-ejs in koa now.

**Pull request closed without merging**
